apiVersion: apps/v1
kind: Deployment
metadata:
  name: ligat-al-dev
  namespace: dev
  labels:
    app: ligat-al-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ligat-al-dev
  template:
    metadata:
      labels:
        app: ligat-al-dev
    spec:
      containers:
      - name: ligat-al-dev
        image: nrdevac1/la:v1
        ports:
        - containerPort: 80
        resources:
          limits: 
            memory: "1000Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ligat-al-dev-svc
spec:
  selector:
    app: ligat-al-dev
  ports:
  - port: 80
    targetPort: 80
    name: ligat-al-dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ligat-al-dev
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: ligat-al-dev-svc
            port:
              number: 80


