apiVersion: apps/v1
kind: Deployment
metadata:
  name: ligat-al-prod
  namespace: prod
  labels:
    app: ligat-al-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ligat-al-prod
  template:
    metadata:
      labels:
        app: ligat-al-prod
    spec:
      containers:
      - name: ligat-al-prod
        image: nrdevac1/la-prod:v1
        ports:
        - containerPort: 80
        resources:
          limits: 
            memory: "1000Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ligat-al-prod-svc
spec:
  selector:
    app: ligat-al-prod
  ports:
  - port: 80
    targetPort: 80
    name: ligat-al-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ligat-al-prod-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ligat-al-prod-svc
            port:
              number: 80
